name: Deploy NestJS to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar código a EC2
        run: |
          rsync -avz --exclude node_modules --exclude .git ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app

      - name: Instalar dependencias y reiniciar app
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app
            npm install
            npm run build
            pm2 stop all || true
            pm2 start dist/main.js --name nest-app
          EOF
